language: python
python:
  - 2.7
  - 3.3  # probably irrelevant but so far supporting it has been free
  - 3.4
  - 3.5
  - 3.6
  # as of 2016-11-25, plain "pypy" is the ancient 2.5.0, and this is
  # the only other option:
  - pypy-5.3.1
sudo: false

before_install:
  - pip install -r test-requirements.txt
  - pip install codecov

script:
  - py.test --cov=h11 --cov-config=.coveragerc h11

after_success:
  - codecov
