language: python
python:
  - 3.3  # probably irrelevant but so far supporting it has been free
  - 3.4
  - 3.5
sudo: false

before_install:
  - pip install -r test-requirements.txt

script:
  - py.test --cov=h11 --cov-config=.coveragerc h11

after_success:
  - codecov
